// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world_1
List rcpp_hello_world_1();
RcppExport SEXP _MulEA_rcpp_hello_world_1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world_1());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world_2
List rcpp_hello_world_2();
RcppExport SEXP _MulEA_rcpp_hello_world_2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world_2());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MulEA_rcpp_hello_world_1", (DL_FUNC) &_MulEA_rcpp_hello_world_1, 0},
    {"_MulEA_rcpp_hello_world_2", (DL_FUNC) &_MulEA_rcpp_hello_world_2, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MulEA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
