# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world_1 <- function() {
    .Call('_MulEA_rcpp_hello_world_1', PACKAGE = 'MulEA')
}

rcpp_hello_world_2 <- function() {
    .Call('_MulEA_rcpp_hello_world_2', PACKAGE = 'MulEA')
}

